DROP TABLE IF EXISTS FLOTA;
CREATE TABLE FLOTA(
ID INT AUTO_INCREMENT PRIMARY KEY,
MARCA VARCHAR(25) NOT NULL,
MODELO VARCHAR(25) NOT NULL,
MATRICULA VARCHAR(25) NOT NULL,
FECHA_ENTRADA DATE NOT NULL);

INSERT INTO FLOTA VALUES(DEFAULT,'BOEING','787','CNP-123','2024-05-19');